<?php

namespace Database\Seeders;

use App\Models\Purchase;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RegenerateStockSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $year = 2025;
        $this->command->info("Regenerating Stock for Purchases in Year $year...");

        // Get all completed purchases for 2025
        // We assume these were generated by the seeder and stock wasn't added.
        // To be safe, we could check if stock is 0, but products might have had previous stock.
        // Just applying the quantity addition is the direct fix for "stock didn't increase".
        
        $purchases = Purchase::with('items.product')
            ->whereYear('purchase_date', $year)
            ->where('status', 'completed')
            ->get();

        $count = 0;
        $totalItems = 0;

        DB::transaction(function () use ($purchases, &$count, &$totalItems) {
            foreach ($purchases as $purchase) {
                foreach ($purchase->items as $item) {
                    $product = $item->product;
                    if ($product) {
                        // Increment stock
                        $product->increment('stock', $item->quantity);
                        $totalItems++;
                    }
                }
                $count++;
            }
        });

        $this->command->info("Processed $count Purchases.");
        $this->command->info("Updated stock for $totalItems Purchase Items.");
    }
}
