name: Deploy Demo Site

on:
  push:
    branches:
      - demo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite3, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install Composer Dependencies
        run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader --no-dev

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM Dependencies & Build
        run: |
          npm ci
          npm run build

      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME_DEMO }}
          password: ${{ secrets.FTP_PASSWORD_DEMO }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
            .env.example
            .env.production
            .env.docker
            .editorconfig
            .cpanel.yml
            docker-compose.yml
            storage/app/public/**
            storage/logs/**
            storage/framework/cache/data/**
            storage/framework/sessions/**
            storage/framework/testing/**
            storage/framework/views/**
            tests/**
            phpunit.xml
            README.md
