name: Deploy Main Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, libxml, phar, simplexml, xmlreader, xmlwriter, zip, zlib

      - name: Install Composer Dependencies
        run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader --no-dev

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM Dependencies & Build
        run: |
          npm ci
          npm run build

      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: kopkarskf.com
          username: ${{ secrets.FTP_USERNAME_MAIN }}
          password: ${{ secrets.FTP_PASSWORD_MAIN }}
          protocol: ftp
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
            .cpanel.yml
            DEPLOYMENT.md
